language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
    - DJANGO="Django>=1.4,<1.5"
    - DJANGO="Django>=1.5,<1.6"
    - DJANGO="Django>=1.6,<1.7"
    - DJANGO="Django>=1.7,<1.8"
install:
  - pip install $DJANGO -r requirements.txt
matrix:
    exclude:
        # Python 2.6 support has been dropped in Django 1.7
        - python: "2.6"
          env: DJANGO="Django>=1.7,<1.8"
        # Support for python 3 was added in Django 1.5
        - python: "3.3"
          env: DJANGO="Django>=1.4,<1.5"
        - python: "3.2"
          env: DJANGO="Django>=1.4,<1.5"
# command to run tests
script:
  - cd testproject ; python -W error:"":"":0 manage.py test wiki --settings=testproject.settings.travis --traceback
notifications:
    irc:
        - "irc.freenode.org#django-wiki"
