cache: pip

language: python

matrix:
  include:
  - python: 3.4
    dist: trusty
    sudo: false
    env: LINT="yes"
  - python: 3.4
    dist: trusty
    sudo: false
    env: DJANGO="1.11"
  - python: 3.4
    dist: trusty
    sudo: false
    env: DJANGO="2.0"

  - python: 3.5
    dist: trusty
    sudo: false
    env: DJANGO="1.11"
  - python: 3.5
    dist: trusty
    sudo: false
    env: DJANGO="2.0"
  - python: 3.5
    dist: trusty
    sudo: false
    env: DJANGO="2.1"
  - python: 3.5
    dist: trusty
    sudo: false
    env: DJANGO="2.2"

  - python: 3.6
    dist: trusty
    sudo: false
    env: DJANGO="1.11"
  - python: 3.6
    dist: trusty
    sudo: false
    env: DJANGO="2.0"
  - python: 3.6
    dist: trusty
    sudo: false
    env: DJANGO="2.1"
  - python: 3.6
    dist: trusty
    sudo: false
    env: DJANGO="2.2"

  - python: 3.7
    dist: xenial
    sudo: true
    env: DJANGO="2.0"
  - python: 3.7
    dist: xenial
    sudo: true
    env: DJANGO="2.1"
  - python: 3.7
    dist: xenial
    sudo: true
    env: DJANGO="2.2"

  - python: pypy
    dist: trusty
    sudo: false
    env: DJANGO="1.11"

addons:
  apt:
    packages:
      - libjpeg8
      - libjpeg8-dev

install:
  - pip install tox tox-travis codecov

script:
  - tox

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - codecov
