cache: pip

dist: xenial
addons:
  apt:
    packages:
      - libjpeg8
      - libjpeg8-dev

language: python

matrix:
  include:
  - python: 3.5
    env: DJANGO="2.2"

  - python: 3.6
    env: DJANGO="2.2"
  - python: 3.6
    env: DJANGO="3.0"
  - python: 3.6
    env: DJANGO="3.1"
  - python: 3.6
    env: LINT=yes

  - python: 3.7
    env: DJANGO="2.2"
  - python: 3.7
    env: DJANGO="3.0"
  - python: 3.7
    env: DJANGO="3.1"

  - python: 3.8
    dist: bionic
    sudo: true
    env: DJANGO="2.2"
  - python: 3.8
    dist: bionic
    sudo: true
    env: DJANGO="3.0"
  - python: 3.8
    dist: bionic
    sudo: true
    env: DJANGO="3.1"

install:
  - pip install tox tox-travis codecov

script:
  - python3 -c "import sqlite3;print(sqlite3.sqlite_version)"
  - tox

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - codecov
