# Because Python 3.6 is available on GCE
dist: trusty

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - LINT="yes"
  - DJANGO="1.8"
  - DJANGO="1.9"
  - DJANGO="1.10"
  - DJANGO="1.11"

matrix:
  exclude:
  - python: "3.4"
    env: LINT="yes"
  - python: "3.5"
    env: LINT="yes"
  - python: "3.6"
    env: LINT="yes"
  - python: "3.6"
    env: DJANGO="1.8"
  - python: "3.6"
    env: DJANGO="1.9"
  - python: "3.6"
    env: DJANGO="1.10"

addons:
  apt:
    packages:
      - libjpeg8
      - libjpeg8-dev

install:
  - pip install tox\>=2.1 tox-travis codecov

script:
  - tox

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - codecov
